#pragma config(Motor,  port1,           masterMotor,   tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           lift1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           lift2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           conveyor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           conveyor1,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          slaveMotor1,   tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

// function prototypes
void moveLift(int power);

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "ehs.h";

/** Code executed before autonomous. Usually includes resetting encoders, setting servos, etc.
 */
void pre_auton()
{
  bStopTasksBetweenModes = true; // do not set this to false.
}

/** Code to be executed during the 15 second autonomous period.
 * <br />The goal is to knock both of the large balls off of the rack into the scoring zone.
 * <br />Instructions:<br /><ol>
 * <li>Raise the lift above the 12 in. bar.</li>
 * <li>Orient the robot so that it is facing the large ball nearest to it.</li>
 * <li>When the autonomous period starts, the robot will go forward and knock the large ball into the scoring zone. Then, it will return to its starting position. 
 * Once the robot gets back to the starting position, you have five seconds to rotate it so that it is facing the second large ball.</li> 
 * </ol>
 * After that the robot will go forward and knock the second large ball off of the rack. It will remain there until user control starts.
 */
task autonomous()
{
	move(127, 35);
	wait1Msec(300);
	move(-85, -50);
	wait1Msec(1000);
	move(127, 35);
	wait1Msec(2500);
	move(-127, 0);
	wait1Msec(2000);
	stopMoving();
}

task usercontrol()
{
	while (true)
	{
		move(quadraticAcceleration((vexRT[Ch3])), quadraticAcceleration(vexRT[Ch1]));

		// move the lift
		moveLift(quadraticAcceleration(vexRT[Ch2]));

		// intake system
		if (vexRT[Btn5D] == 1)
		{
			motor[conveyor1] = -127;
		}
		else if (vexRT[Btn5U] == 1)
		{
			motor[conveyor1] = 127;
		}
		else
		{
			motor[conveyor1] = 0;
		}

		if (vexRT[Btn6D] == 1)
		{
			motor[conveyor2] = -127;
		}
		else if (vexRT[Btn6U] == 1)
		{
			motor[conveyor2] = 127;
		}
		else
		{
			motor[conveyor2] = 0;
		}
	}
}

/** Moves the lift at a specified power.
 * Sets motor[lift1] and motor[lift2] to <code>power</code>
 */
void moveLift(int power/*! The power to set the motor to. Should be an integer between 127 and -127*/)
{
	motor[lift1] = power;
	motor[lift2] = power;
}
