#pragma config(Motor,  port1,           masterMotor,   tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           lift1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           lift2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           conveyor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           conveyor1,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          slaveMotor1,   tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// the robot travels 49 inches in 2 sec at max power.
// the rate is 25 inches / second
#include "ehs.h";

task main()
{
	move(127, 0);
	wait1Msec(2000);
}
