#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl12, limit,          sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,            ,             tmotorVex269, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,            ,             tmotorVex269, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port4,            ,             tmotorVex269, openLoop, reversed, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port5,            ,             tmotorVex269, openLoop, reversed, encoder, encoderPort, I2C_4, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ehs.h";

/** Test user control on a robot with 4 motors driving it in tank mode. 
 * This program never actually ran on the robot. It was just for testing and experimentation.
 */

task main()
{
	while (true)
	{
		if (SensorValue(limit) == 0)
		{
			motor[port2] = quadraticAcceleration(vexRT[Ch2]);
			motor[port3] = quadraticAcceleration(vexRT[Ch2]);
			motor[port4] = quadraticAcceleration(vexRT[Ch3]);
			motor[port5] = quadraticAcceleration(vexRT[Ch3]);
			if (vexRT[Btn8R] == 1)
			{
				motor[port2] = 0;
				motor[port3] = 0;
				motor[port4] = 0;
				motor[port5] = 0;
			}
		}
		else
		{
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port4] = 0;
			motor[port5] = 0;
		}
	}
}
