#pragma config(Motor,  port2,           frontRight,    tmotorVex269, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ehs.h";

/** Allows the robot to drive around in tank mode.
 */

task main()
{
	while (true)
	{
			motor[port2] = quadraticAcceleration(vexRT[Ch3]);
			motor[port3] = quadraticAcceleration(vexRT[Ch2]);
	}
}
