#pragma config(Sensor, dgtl1,  theEncoder,     sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/** This is a dummy program to check whether an encoder is working properly.
 * The sensor value may be viewed in the debugger. The shaft must be manually turned. 
 */
task main()
{
	while (true)
	{
		int x = theEncoder;
	}
}
