#pragma config(Motor,  port2,           masterMotor,   tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           slaveMotor1,   tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lift1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lift2,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ehs.h"

int master = 0; // master motor speed
int slave = 0; // slave motor speed
int turn = 0; // the amount by which it turns

/** Enables movement of the lift.
 */

task main()
{
	while (true)
	{
		master = quadraticAcceleration(vexRT[Ch3]);
		slave = quadraticAcceleration(vexRT[Ch3]);

		// apply turns
		turn = vexRT[Ch1];
		master += turn;
		slave -= turn;

		// assign values to motors
		motor[masterMotor] = validateSpeed(master);
		motor[slaveMotor1] = validateSpeed(slave);
		
		// move lift
		motor[port4] = vexRT[Ch2];
		motor[port5] = vexRT[Ch2];
	}
}
